language: php

sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --prefer-dist

script: vendor/bin/phpunit -c phpunit.xml.dist
